// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orhcenzsvsiogpvysnfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yaGNlbnpzdnNpb2dwdnlzbmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NTMyNzQsImV4cCI6MjA3ODAyOTI3NH0.4Rfx5NKB4Vjux_be3ymLZA14MBxuVvohJCzF_rxBgM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});